version: "3.9"
services:
  web-app:
    container_name: web-app
    build:
      context: ./web-app_service/
      dockerfile: Dockerfile.web-app
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - USER_DATA_DIR=${USER_DATA_DIR}
      - EVENT_DATA_DIR=${EVENT_DATA_DIR}
      - NON_AVATAR_PATH=${NON_AVATAR_PATH}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_UPDATE_SECONDS=${REDIS_UPDATE_SECONDS}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - internet
    depends_on:
      - caching-service
      - mailer-service
      - postgres

  mailer-service:
    container_name: mailer
    build:
      context: mailer_service/
      dockerfile: Dockerfile
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - internet

  caching-service:
    container_name: redis
    image: redis:7.4-rc1-alpine3.20
    networks:
      - internet

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - internet

  pgadmin:
    container_name: pgadmin_container
    build:
      context: ./pgadmin_service/
      dockerfile: Dockerfile.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "5200:80"
    depends_on:
      - postgres
    networks:
      - internet

networks:
  internet:
    name: internet
    driver: bridge

