version: "3.9"
services:
  flask-app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SURNAME=${SURNAME}
      - NAME=${NAME}
      - NICKNAME=${NICKNAME}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
    networks:
      - internet
    depends_on:
      - caching-service
      - mailer-service
      - postgres

  mailer-service:
    container_name: mailer
    build:
      context: mailer_service/
      dockerfile: Dockerfile
    ports:
      - "5150:5150"
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - internet

  document-service:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "5050:80"
    volumes:
      - ./docs/build/html/:/usr/share/nginx/html:ro

  caching-service:
    container_name: redis
    image: redis:7.4-rc1-alpine3.20
    ports:
      - "5100:6379"
    networks:
      - internet

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "volunteerium"
      POSTGRES_USER: "volunteer"
      POSTGRES_PASSWORD: "volunteer"
    ports:
      - "5250:5432"
    volumes:
      - /data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "volunteer@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "volunteer"
    ports:
      - "5200:80"


networks:
  internet:
    name: internet
    driver: bridge

