version: "3.9"
services:
  flask-app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - internet
    depends_on:
      - caching-service
  document-service:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "5050:80"
    volumes:
      - ./docs/build/html/:/usr/share/nginx/html:ro
    networks:
      - internet
  caching-service:
    container_name: redis
    image: redis:alpine
    ports:
      - "5100:6379"
    networks:
      - internet
networks:
  internet:
    name: internet
    driver: bridge

