SECRET_KEY = 'dev'
HOST = '0.0.0.0'
PORT = 5000
DEBUG = True
DB_PATH = "db/volunteerium.db"
USER_DATA_DIR = "users_avatars"
EVENT_DATA_DIR = "events_avatars"
NON_AVATAR_PATH = "users_avatars/default.jpg"
REDIS_HOST = "redis"
# REDIS_HOST = "wsl.localhost"
REDIS_PORT = 6379
REDIS_UPDATE_SECONDS = 10
MAILER_HOST = "mailer"
# MAILER_HOST = "127.0.0.1"
MAILER_PORT = 5150
DB_HOST = "postgres"
DB_PORT = "5432"
DB_NAME = "volunteerium"
DB_USER = "volunteer"
DB_PASS = "volunteer"
