SECRET_KEY = 'dev'
HOST = '0.0.0.0'
PORT = 5000
DEBUG = True
DB_PATH = "db/volunteerium.db"
DATA_DIR = "users_avatars"
NON_AVATAR_PATH = "users_avatars/default.jpg"
REDIS_HOST = "redis"
# REDIS_HOST = "wsl.localhost"
REDIS_PORT = 6379
