FROM dpage/pgadmin4

COPY db_adder.py /tmp/db_adder.py
COPY input_db.json.template /tmp/input_db.json.template
USER root
ENTRYPOINT ["/bin/sh", "-c", ". /venv/bin/activate && cd /tmp && python3 db_adder.py &"]

