FROM dpage/pgadmin4

COPY db_adder.py /tmp/db_adder.py
COPY input_db.json.template /tmp/input_db.json.template
RUN ["/bin/sh", "-c", "/venv/bin/python3 /tmp/db_adder.py &> /tmp/logs"]
ENTRYPOINT ["/entrypoint.sh"]
