FROM dpage/pgadmin4

COPY db_adder.py /tmp/db_adder.py
COPY input_db.json.template /tmp/input_db.json.template
ENTRYPOINT ["/bin/sh", "-c", ". /venv/bin/activate && python3 /tmp/db_adder.py &> logs && /entrypoint.sh"]


