name: main
on:
  push:
    branches: ["feature_17"]
  pull_request:
    branches: ["feature_17"]

jobs:
  before_script:
    runs-on: self-hosted
    steps:
      - name: Test
        uses: actions/checkout@v3

      - name: Test
        run: python3 -m venv venv

      - name: Test
        run: | 
          source venv/bin/activate
          pip install poetry
          poetry install

      - name: Test
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv

  linting:
    runs-on: self-hosted
    steps:


      - name: Test
        run: source venv/bin/activate


      - name: Test
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Test
        run: echo "starting time is $(date)" > log-CI

      - name: Test
        run: ruff check --fix

      - name: Test
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: Test
        uses: actions/upload-artifact@v4
        with:
            name: logfile
            path: log-CI

  testing:
    runs-on: self-hosted
    steps:
       
      - name: Test
        run: source venv/bin/activate


      - name: Test
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Test
        run: pytest


      - name: Test
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: Test
        uses: actions/upload-artifact@v4
        with:
          name: logfile
          path: log-CI

  documentation:
    runs-on: self-hosted
    steps:
       
      - name: Test
        run: source venv/bin/activate

      - name: Test
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Test
        run: cd docs

      - name: Test
        run: python3 create_all_docs.py


      - name: Test
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: Test
        uses: actions/upload-artifact@v4
        with:
            name: logfile
            path: log-CI

      - name: Test
        uses: actions/upload-artifact@v4
        with:
            name: docsdir
            path: $CI_PROJECT_DIR/docs/

  deploy:
    runs-on: self-hosted
    steps:
       
      - name: Test
        run: source venv/bin/activate


      - name: Test
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Test
        run: docker-compose down

      - name: Test
        run: docker-compose up -d


      - name: Test
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: Test
        uses: actions/upload-artifact@v4
        with:
          name: logfile
          path: log-CI