name: Main CI
on:
  push:
    branches: ["feature_17"]
  pull_request:
    branches: ["feature_17"]

jobs:
  before_script:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: python3 -m venv venv
      - run: source venv/bin/activate
      - run: pip install poetry
      - run: poetry install
      - uses: actions/upload-artifact@v4
        with:
          path: venv

  linting:
    runs-on: self-hosted
    steps:
      pre:
        - run: source venv/bin/activate
      main:
        - name: Checkout code
          uses: actions/checkout@v3
        - run: echo "starting time is $(date)" > log-CI
        - run: ruff check --fix
      post:
        - run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        - uses: actions/upload-artifact@v4
          with:
            - path: flaskr/
            - path: log-CI

  testing:
    runs-on: self-hosted
    steps:
      pre:
        - run: source venv/bin/activate
      main:
        - name: Checkout code
          uses: actions/checkout@v3
        - run: pytest

      post:
        - run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        - uses: actions/upload-artifact@v4
          with:
            - path: log-CI
  documentation:
    runs-on: self-hosted
    steps:
      pre:
        - run: source venv/bin/activate
      main:
        - name: Checkout code
          uses: actions/checkout@v3
        - run: cd docs
        - run: python3 create_all_docs.py
      post:
        - run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        - uses: actions/upload-artifact@v4
          with:
            - path: log-CI
            - path: $CI_PROJECT_DIR/docs/

  deploy:
    runs-on: self-hosted
    steps:
      pre:
        - run: source venv/bin/activate
      main:
        - name: Checkout code
          uses: actions/checkout@v3
        - run: docker-compose down
        - run: docker-compose up -d

      post:
        - run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        - uses: actions/upload-artifact@v4
          with:
            - path: log-CI