name: main
on:
  push:
    branches: ["feature_17"]
  pull_request:
    branches: ["feature_17"]

jobs:
  before_script:
    runs-on: self-hosted
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3

      - name: python3 -m venv venv
        run: python3 -m venv venv

      - name: poetry install
        run: | 
          source venv/bin/activate
          pip install poetry
          poetry install
          chmod ugo+rwx venv/bin/*

      - name: venv
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv

  linting:
    needs: before_script
    runs-on: self-hosted
    steps:


      - name: checkout
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: linting
        run: | 
          source venv/bin/activate
          ruff check --fix

      - name: echo "starting time is $(date)" > log-CI
        run: echo "starting time is $(date)" > log-CI

      - name: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: logfile
        uses: actions/upload-artifact@v4
        with:
            name: logfile
            path: log-CI

  testing:
    needs: [linting, before_script]
    runs-on: self-hosted
    steps:
       
      - name: checkout
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: pytest
        run: |
          source venv/bin/activate
          pytest

      - name: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: logfile
        uses: actions/upload-artifact@v4
        with:
          name: logfile
          path: log-CI

  documentation:
    needs: [testing, linting, before_script]
    runs-on: self-hosted
    steps:


      - name: checkout
        uses: actions/checkout@v3

      - name: download-artifacts
        uses: actions/download-artifact@v4

      - name: creating documentation
        run: |
          source venv/bin/activate
          cd docs
          python3 create_all_docs.py

      - name: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: logfile
        uses: actions/upload-artifact@v4
        with:
            name: logfile
            path: log-CI

      - name: docsdir
        uses: actions/upload-artifact@v4
        with:
            name: docsdir
            path: $CI_PROJECT_DIR/docs/

  deploy:
    needs: [testing, linting, before_script, documentation]
    runs-on: self-hosted
    steps:
       
      - name: checkout
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: docker-compose down
        run: docker-compose down

      - name: docker-compose up -d
        run: docker-compose up -d


      - name: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI
        run: echo "$CI_JOB_NAME is $CI_JOB_STATUS" >> log-CI

      - name: logfile
        uses: actions/upload-artifact@v4
        with:
          name: logfile
          path: log-CI