name: CI/CD

on:
  push:
    branches: [feature_17]

jobs:
  linting:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python environment and linting
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install poetry
          poetry install
          echo "starting time is $(date)" > log-CI
          ruff check --fix


      - name: Log job status
        run: |
          echo "$GITHUB_JOB is ok" >> log-CI

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logfile
          path: ./log-CI

      - name: Upload venv
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: ./venv
      

  testing:
    runs-on: self-hosted
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: logfile
          path: ./

      - name: Download venv
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: ./venv

      - name: Setup Python environment
        run: |
          ls
          source venv/bin/activate
          pytest
          echo "$GITHUB_JOB is ok" >> ./log-CI

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logfile2
          path: ./log-CI

      

  documentation:
    runs-on: self-hosted
    needs: [testing, linting]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download venv
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: ./venv

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: logfile2
          path: ./

      - name: Setup Python environment
        run: |
          source venv/bin/activate
      - name: Documentation
        run: |
          cd docs
          python3 create_all_docs.py
          cd ..
      - name: Log job status
        run: |
          echo "$GITHUB_JOB is ok" >> ./log-CI
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logfile3
          path: ./log-CI


  deploy:
    runs-on: self-hosted
    needs: [testing, linting, documentation]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: ./docs

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: logfile3
          path: ./

      - name: Deploy
        run: |
          docker-compose down
          docker-compose up -d
      - name: Log job status
        run: |
          echo "$GITHUB_JOB is ok" >> ./log-CI

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logfile4
          path: ./log-CI

  notify:
    runs-on: self-hosted
    needs: [testing, linting, deploy, documentation]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: logfile4
          path: ./
      - name: Notify
        run: |
          sh ci-notify.sh log-CI $GITHUB_REF_NAME $GITHUB_REPOSITORY
      
  notify-on-failure:
    runs-on: self-hosted
    steps:
      - name: Notify on failure
        if: ${{ failure() }}
        run: |
          echo "Pipeline failed." > log-CI
          sh ci-notify.sh log-CI $GITHUB_REF_NAME $GITHUB_REPOSITORY